language: ruby
rvm:
- 2.5.1
script:
- bundle exec rails db:migrate
- bundle exec rspec -fd spec
deploy:
  provider: heroku
  api_key:
    secure: CIsht67D5ScCmfEp0EDVl04TJb0mnwAfJNr0MsCkkzU3TxLN4vJxbrzvN79HP1Pnfk/cEQCmaBcEp/P4ihJHDakCOrg6RqheNg6524ORTXINL6XiGzdpfWTOGqbHwULNHTG3iCGo2djRLHVaKZ9xggLkxp4UKmfH9/ip6mN/mTCGCC/vURN9hUqcuMrIByD4KDstCTx+JyagfOrna5VKhMktbRaQY09ZPruSxvEhrMUdYYBo1MnlnPojrcqi+y2MUfOS7BxXA5Ur7DLqmYcwCDE7pvPefmY3GWVkIT6n00Bbyr5XzG/klCbT6PbhZaZBG25PeUwXLMpsgSIX1yyPiNguJYSGL9qoKW/LvI2tMokxoC+gaVFcf4onbFzeGovm75oy5Uw8rvWvRjizClC+jvyi3gNQwYbp/hhSGbag6zdrXEbyCf6SBvbZPlCBBu6qLk9lXBZmRsdGLtmxfG+ejOsWYMnXv4baGHrcRdo+GLWm540ORQSZcS8eUvYck1a/5Hcwr643sOkMheR0gipBVr/ptkwY1yjLdeMlCSn3UwSkWqvB5oWVsPe13g8Jv/sWNVyFpYd7SVTRkfN3jarRAcZtv1SmAaaKUdpVUMz5nPiGOWZOJ1TRXUffDHiBG5+eRr789AJ5gzqV1hDPtGkZJj5Kgqn71f8Ib0FMMxAYS6E=
  app: rocky-fjord-88573
  on:
    repo: haapseem/ratebeer
